# Generated by Django 4.2 on 2023-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_myfestivalplanning'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myfestivalplanning',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='myfestivalplanning',
            name='festivals',
            field=models.ManyToManyField(to='main_app.festival'),
        ),
        migrations.RemoveField(
            model_name='myfestivalplanning',
            name='festival',
        ),
    ]
