# Generated by Django 4.2 on 2023-04-19 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_alter_myfestivalplanning_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFestivalPlanning',
            new_name='MyFestival',
        ),
    ]
