# Generated by Django 4.2 on 2023-04-20 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='my_festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.myfestival'),
            preserve_default=False,
        ),
    ]
