# Generated by Django 4.2 on 2023-04-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_task_my_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.festival'),
            preserve_default=False,
        ),
    ]
