# Generated by Django 4.2 on 2023-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_task_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suitecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('own', 'I own this'), ('need', 'I need to purchase this'), ('borrow', 'I am borrowing this')], default='own', max_length=100)),
                ('item_name', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
            ],
        ),
    ]
