# Generated by Django 4.2 on 2023-04-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_suitecase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suitecase',
            new_name='Suitcase',
        ),
    ]
