# Generated by Django 4.2 on 2023-04-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_suitecase_suitcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitcase',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.festival'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suitcase',
            name='my_festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.myfestival'),
            preserve_default=False,
        ),
    ]
