# Generated by Django 4.2 on 2023-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_suitcase_festival_suitcase_my_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcase',
            name='status',
            field=models.CharField(choices=[('I own ', 'I own this'), ('I need to purchase', 'I need to purchase this'), ('I will borrow', 'I am borrowing this')], max_length=100),
        ),
    ]
