# Generated by Django 4.2 on 2023-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_suitcase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcase',
            name='status',
            field=models.CharField(choices=[('I own this', 'I own this'), ('I need to purchase', 'I need to purchase this'), ('I will borrow', 'I am borrowing this')], default='I own this', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
